spring:
  profiles:
    active: development
  main:
    banner-mode: "off"
  application:
    name: "Test-Consul-Service"
    
security:
  basic:
    enabled: false 

management:
  security:
    enabled: false
  context-path: /   